// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dnsimple;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ContactArgs extends com.pulumi.resources.ResourceArgs {

    public static final ContactArgs Empty = new ContactArgs();

    /**
     * The primary address line (street address, building number, etc.).
     * 
     */
    @Import(name="address1", required=true)
    private Output<String> address1;

    /**
     * @return The primary address line (street address, building number, etc.).
     * 
     */
    public Output<String> address1() {
        return this.address1;
    }

    /**
     * The secondary address line (apartment, suite, floor, etc.).
     * 
     */
    @Import(name="address2")
    private @Nullable Output<String> address2;

    /**
     * @return The secondary address line (apartment, suite, floor, etc.).
     * 
     */
    public Optional<Output<String>> address2() {
        return Optional.ofNullable(this.address2);
    }

    /**
     * The city where the contact is located.
     * 
     */
    @Import(name="city", required=true)
    private Output<String> city;

    /**
     * @return The city where the contact is located.
     * 
     */
    public Output<String> city() {
        return this.city;
    }

    /**
     * The two-letter ISO country code (e.g., &#34;US&#34;, &#34;CA&#34;, &#34;IT&#34;) for the contact&#39;s location.
     * 
     */
    @Import(name="country", required=true)
    private Output<String> country;

    /**
     * @return The two-letter ISO country code (e.g., &#34;US&#34;, &#34;CA&#34;, &#34;IT&#34;) for the contact&#39;s location.
     * 
     */
    public Output<String> country() {
        return this.country;
    }

    /**
     * The contact&#39;s email address.
     * 
     */
    @Import(name="email", required=true)
    private Output<String> email;

    /**
     * @return The contact&#39;s email address.
     * 
     */
    public Output<String> email() {
        return this.email;
    }

    /**
     * The contact&#39;s fax number. Use international format with country code (e.g., &#34;+1.8491234567&#34; for US numbers).
     * 
     */
    @Import(name="fax")
    private @Nullable Output<String> fax;

    /**
     * @return The contact&#39;s fax number. Use international format with country code (e.g., &#34;+1.8491234567&#34; for US numbers).
     * 
     */
    public Optional<Output<String>> fax() {
        return Optional.ofNullable(this.fax);
    }

    /**
     * The first name of the contact person.
     * 
     */
    @Import(name="firstName", required=true)
    private Output<String> firstName;

    /**
     * @return The first name of the contact person.
     * 
     */
    public Output<String> firstName() {
        return this.firstName;
    }

    /**
     * The job title or position of the contact person within the organization.
     * 
     */
    @Import(name="jobTitle")
    private @Nullable Output<String> jobTitle;

    /**
     * @return The job title or position of the contact person within the organization.
     * 
     */
    public Optional<Output<String>> jobTitle() {
        return Optional.ofNullable(this.jobTitle);
    }

    /**
     * A descriptive label for the contact to help identify it.
     * 
     */
    @Import(name="label")
    private @Nullable Output<String> label;

    /**
     * @return A descriptive label for the contact to help identify it.
     * 
     */
    public Optional<Output<String>> label() {
        return Optional.ofNullable(this.label);
    }

    /**
     * The last name of the contact person.
     * 
     */
    @Import(name="lastName", required=true)
    private Output<String> lastName;

    /**
     * @return The last name of the contact person.
     * 
     */
    public Output<String> lastName() {
        return this.lastName;
    }

    /**
     * The name of the organization or company associated with the contact.
     * 
     */
    @Import(name="organizationName")
    private @Nullable Output<String> organizationName;

    /**
     * @return The name of the organization or company associated with the contact.
     * 
     */
    public Optional<Output<String>> organizationName() {
        return Optional.ofNullable(this.organizationName);
    }

    /**
     * The contact&#39;s phone number. Use international format with country code (e.g., &#34;+1.4012345678&#34; for US numbers).
     * 
     */
    @Import(name="phone", required=true)
    private Output<String> phone;

    /**
     * @return The contact&#39;s phone number. Use international format with country code (e.g., &#34;+1.4012345678&#34; for US numbers).
     * 
     */
    public Output<String> phone() {
        return this.phone;
    }

    /**
     * The postal code, ZIP code, or equivalent for the contact&#39;s location.
     * 
     */
    @Import(name="postalCode", required=true)
    private Output<String> postalCode;

    /**
     * @return The postal code, ZIP code, or equivalent for the contact&#39;s location.
     * 
     */
    public Output<String> postalCode() {
        return this.postalCode;
    }

    /**
     * The state, province, or region where the contact is located.
     * 
     */
    @Import(name="stateProvince", required=true)
    private Output<String> stateProvince;

    /**
     * @return The state, province, or region where the contact is located.
     * 
     */
    public Output<String> stateProvince() {
        return this.stateProvince;
    }

    private ContactArgs() {}

    private ContactArgs(ContactArgs $) {
        this.address1 = $.address1;
        this.address2 = $.address2;
        this.city = $.city;
        this.country = $.country;
        this.email = $.email;
        this.fax = $.fax;
        this.firstName = $.firstName;
        this.jobTitle = $.jobTitle;
        this.label = $.label;
        this.lastName = $.lastName;
        this.organizationName = $.organizationName;
        this.phone = $.phone;
        this.postalCode = $.postalCode;
        this.stateProvince = $.stateProvince;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ContactArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ContactArgs $;

        public Builder() {
            $ = new ContactArgs();
        }

        public Builder(ContactArgs defaults) {
            $ = new ContactArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param address1 The primary address line (street address, building number, etc.).
         * 
         * @return builder
         * 
         */
        public Builder address1(Output<String> address1) {
            $.address1 = address1;
            return this;
        }

        /**
         * @param address1 The primary address line (street address, building number, etc.).
         * 
         * @return builder
         * 
         */
        public Builder address1(String address1) {
            return address1(Output.of(address1));
        }

        /**
         * @param address2 The secondary address line (apartment, suite, floor, etc.).
         * 
         * @return builder
         * 
         */
        public Builder address2(@Nullable Output<String> address2) {
            $.address2 = address2;
            return this;
        }

        /**
         * @param address2 The secondary address line (apartment, suite, floor, etc.).
         * 
         * @return builder
         * 
         */
        public Builder address2(String address2) {
            return address2(Output.of(address2));
        }

        /**
         * @param city The city where the contact is located.
         * 
         * @return builder
         * 
         */
        public Builder city(Output<String> city) {
            $.city = city;
            return this;
        }

        /**
         * @param city The city where the contact is located.
         * 
         * @return builder
         * 
         */
        public Builder city(String city) {
            return city(Output.of(city));
        }

        /**
         * @param country The two-letter ISO country code (e.g., &#34;US&#34;, &#34;CA&#34;, &#34;IT&#34;) for the contact&#39;s location.
         * 
         * @return builder
         * 
         */
        public Builder country(Output<String> country) {
            $.country = country;
            return this;
        }

        /**
         * @param country The two-letter ISO country code (e.g., &#34;US&#34;, &#34;CA&#34;, &#34;IT&#34;) for the contact&#39;s location.
         * 
         * @return builder
         * 
         */
        public Builder country(String country) {
            return country(Output.of(country));
        }

        /**
         * @param email The contact&#39;s email address.
         * 
         * @return builder
         * 
         */
        public Builder email(Output<String> email) {
            $.email = email;
            return this;
        }

        /**
         * @param email The contact&#39;s email address.
         * 
         * @return builder
         * 
         */
        public Builder email(String email) {
            return email(Output.of(email));
        }

        /**
         * @param fax The contact&#39;s fax number. Use international format with country code (e.g., &#34;+1.8491234567&#34; for US numbers).
         * 
         * @return builder
         * 
         */
        public Builder fax(@Nullable Output<String> fax) {
            $.fax = fax;
            return this;
        }

        /**
         * @param fax The contact&#39;s fax number. Use international format with country code (e.g., &#34;+1.8491234567&#34; for US numbers).
         * 
         * @return builder
         * 
         */
        public Builder fax(String fax) {
            return fax(Output.of(fax));
        }

        /**
         * @param firstName The first name of the contact person.
         * 
         * @return builder
         * 
         */
        public Builder firstName(Output<String> firstName) {
            $.firstName = firstName;
            return this;
        }

        /**
         * @param firstName The first name of the contact person.
         * 
         * @return builder
         * 
         */
        public Builder firstName(String firstName) {
            return firstName(Output.of(firstName));
        }

        /**
         * @param jobTitle The job title or position of the contact person within the organization.
         * 
         * @return builder
         * 
         */
        public Builder jobTitle(@Nullable Output<String> jobTitle) {
            $.jobTitle = jobTitle;
            return this;
        }

        /**
         * @param jobTitle The job title or position of the contact person within the organization.
         * 
         * @return builder
         * 
         */
        public Builder jobTitle(String jobTitle) {
            return jobTitle(Output.of(jobTitle));
        }

        /**
         * @param label A descriptive label for the contact to help identify it.
         * 
         * @return builder
         * 
         */
        public Builder label(@Nullable Output<String> label) {
            $.label = label;
            return this;
        }

        /**
         * @param label A descriptive label for the contact to help identify it.
         * 
         * @return builder
         * 
         */
        public Builder label(String label) {
            return label(Output.of(label));
        }

        /**
         * @param lastName The last name of the contact person.
         * 
         * @return builder
         * 
         */
        public Builder lastName(Output<String> lastName) {
            $.lastName = lastName;
            return this;
        }

        /**
         * @param lastName The last name of the contact person.
         * 
         * @return builder
         * 
         */
        public Builder lastName(String lastName) {
            return lastName(Output.of(lastName));
        }

        /**
         * @param organizationName The name of the organization or company associated with the contact.
         * 
         * @return builder
         * 
         */
        public Builder organizationName(@Nullable Output<String> organizationName) {
            $.organizationName = organizationName;
            return this;
        }

        /**
         * @param organizationName The name of the organization or company associated with the contact.
         * 
         * @return builder
         * 
         */
        public Builder organizationName(String organizationName) {
            return organizationName(Output.of(organizationName));
        }

        /**
         * @param phone The contact&#39;s phone number. Use international format with country code (e.g., &#34;+1.4012345678&#34; for US numbers).
         * 
         * @return builder
         * 
         */
        public Builder phone(Output<String> phone) {
            $.phone = phone;
            return this;
        }

        /**
         * @param phone The contact&#39;s phone number. Use international format with country code (e.g., &#34;+1.4012345678&#34; for US numbers).
         * 
         * @return builder
         * 
         */
        public Builder phone(String phone) {
            return phone(Output.of(phone));
        }

        /**
         * @param postalCode The postal code, ZIP code, or equivalent for the contact&#39;s location.
         * 
         * @return builder
         * 
         */
        public Builder postalCode(Output<String> postalCode) {
            $.postalCode = postalCode;
            return this;
        }

        /**
         * @param postalCode The postal code, ZIP code, or equivalent for the contact&#39;s location.
         * 
         * @return builder
         * 
         */
        public Builder postalCode(String postalCode) {
            return postalCode(Output.of(postalCode));
        }

        /**
         * @param stateProvince The state, province, or region where the contact is located.
         * 
         * @return builder
         * 
         */
        public Builder stateProvince(Output<String> stateProvince) {
            $.stateProvince = stateProvince;
            return this;
        }

        /**
         * @param stateProvince The state, province, or region where the contact is located.
         * 
         * @return builder
         * 
         */
        public Builder stateProvince(String stateProvince) {
            return stateProvince(Output.of(stateProvince));
        }

        public ContactArgs build() {
            if ($.address1 == null) {
                throw new MissingRequiredPropertyException("ContactArgs", "address1");
            }
            if ($.city == null) {
                throw new MissingRequiredPropertyException("ContactArgs", "city");
            }
            if ($.country == null) {
                throw new MissingRequiredPropertyException("ContactArgs", "country");
            }
            if ($.email == null) {
                throw new MissingRequiredPropertyException("ContactArgs", "email");
            }
            if ($.firstName == null) {
                throw new MissingRequiredPropertyException("ContactArgs", "firstName");
            }
            if ($.lastName == null) {
                throw new MissingRequiredPropertyException("ContactArgs", "lastName");
            }
            if ($.phone == null) {
                throw new MissingRequiredPropertyException("ContactArgs", "phone");
            }
            if ($.postalCode == null) {
                throw new MissingRequiredPropertyException("ContactArgs", "postalCode");
            }
            if ($.stateProvince == null) {
                throw new MissingRequiredPropertyException("ContactArgs", "stateProvince");
            }
            return $;
        }
    }

}
