// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dnsimple;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.deployment.InvokeOutputOptions;
import com.pulumi.dnsimple.Utilities;
import com.pulumi.dnsimple.inputs.GetCertificateArgs;
import com.pulumi.dnsimple.inputs.GetCertificatePlainArgs;
import com.pulumi.dnsimple.inputs.GetRegistrantChangeCheckArgs;
import com.pulumi.dnsimple.inputs.GetRegistrantChangeCheckPlainArgs;
import com.pulumi.dnsimple.inputs.GetZoneArgs;
import com.pulumi.dnsimple.inputs.GetZonePlainArgs;
import com.pulumi.dnsimple.outputs.GetCertificateResult;
import com.pulumi.dnsimple.outputs.GetRegistrantChangeCheckResult;
import com.pulumi.dnsimple.outputs.GetZoneResult;
import java.util.concurrent.CompletableFuture;

public final class DnsimpleFunctions {
    /**
     * Get information about a DNSimple SSL certificate.
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.dnsimple.DnsimpleFunctions;
     * import com.pulumi.dnsimple.inputs.GetCertificateArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = DnsimpleFunctions.getCertificate(GetCertificateArgs.builder()
     *             .domain("example.com")
     *             .certificateId(1234)
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static Output<GetCertificateResult> getCertificate(GetCertificateArgs args) {
        return getCertificate(args, InvokeOptions.Empty);
    }
    /**
     * Get information about a DNSimple SSL certificate.
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.dnsimple.DnsimpleFunctions;
     * import com.pulumi.dnsimple.inputs.GetCertificateArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = DnsimpleFunctions.getCertificate(GetCertificateArgs.builder()
     *             .domain("example.com")
     *             .certificateId(1234)
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static CompletableFuture<GetCertificateResult> getCertificatePlain(GetCertificatePlainArgs args) {
        return getCertificatePlain(args, InvokeOptions.Empty);
    }
    /**
     * Get information about a DNSimple SSL certificate.
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.dnsimple.DnsimpleFunctions;
     * import com.pulumi.dnsimple.inputs.GetCertificateArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = DnsimpleFunctions.getCertificate(GetCertificateArgs.builder()
     *             .domain("example.com")
     *             .certificateId(1234)
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static Output<GetCertificateResult> getCertificate(GetCertificateArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("dnsimple:index/getCertificate:getCertificate", TypeShape.of(GetCertificateResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Get information about a DNSimple SSL certificate.
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.dnsimple.DnsimpleFunctions;
     * import com.pulumi.dnsimple.inputs.GetCertificateArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = DnsimpleFunctions.getCertificate(GetCertificateArgs.builder()
     *             .domain("example.com")
     *             .certificateId(1234)
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static Output<GetCertificateResult> getCertificate(GetCertificateArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("dnsimple:index/getCertificate:getCertificate", TypeShape.of(GetCertificateResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Get information about a DNSimple SSL certificate.
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.dnsimple.DnsimpleFunctions;
     * import com.pulumi.dnsimple.inputs.GetCertificateArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = DnsimpleFunctions.getCertificate(GetCertificateArgs.builder()
     *             .domain("example.com")
     *             .certificateId(1234)
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static CompletableFuture<GetCertificateResult> getCertificatePlain(GetCertificatePlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("dnsimple:index/getCertificate:getCertificate", TypeShape.of(GetCertificateResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Get information on the requirements of a registrant change.
     * 
     * &gt; **Note:** The registrant change API is currently in developer preview and is subject to change.
     * 
     * ## Example Usage
     * 
     * Get registrant change requirements for the `example.com` domain and the contact with ID `1234`:
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.dnsimple.DnsimpleFunctions;
     * import com.pulumi.dnsimple.inputs.GetRegistrantChangeCheckArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = DnsimpleFunctions.getRegistrantChangeCheck(GetRegistrantChangeCheckArgs.builder()
     *             .domainId("example.com")
     *             .contactId("1234")
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static Output<GetRegistrantChangeCheckResult> getRegistrantChangeCheck(GetRegistrantChangeCheckArgs args) {
        return getRegistrantChangeCheck(args, InvokeOptions.Empty);
    }
    /**
     * Get information on the requirements of a registrant change.
     * 
     * &gt; **Note:** The registrant change API is currently in developer preview and is subject to change.
     * 
     * ## Example Usage
     * 
     * Get registrant change requirements for the `example.com` domain and the contact with ID `1234`:
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.dnsimple.DnsimpleFunctions;
     * import com.pulumi.dnsimple.inputs.GetRegistrantChangeCheckArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = DnsimpleFunctions.getRegistrantChangeCheck(GetRegistrantChangeCheckArgs.builder()
     *             .domainId("example.com")
     *             .contactId("1234")
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static CompletableFuture<GetRegistrantChangeCheckResult> getRegistrantChangeCheckPlain(GetRegistrantChangeCheckPlainArgs args) {
        return getRegistrantChangeCheckPlain(args, InvokeOptions.Empty);
    }
    /**
     * Get information on the requirements of a registrant change.
     * 
     * &gt; **Note:** The registrant change API is currently in developer preview and is subject to change.
     * 
     * ## Example Usage
     * 
     * Get registrant change requirements for the `example.com` domain and the contact with ID `1234`:
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.dnsimple.DnsimpleFunctions;
     * import com.pulumi.dnsimple.inputs.GetRegistrantChangeCheckArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = DnsimpleFunctions.getRegistrantChangeCheck(GetRegistrantChangeCheckArgs.builder()
     *             .domainId("example.com")
     *             .contactId("1234")
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static Output<GetRegistrantChangeCheckResult> getRegistrantChangeCheck(GetRegistrantChangeCheckArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("dnsimple:index/getRegistrantChangeCheck:getRegistrantChangeCheck", TypeShape.of(GetRegistrantChangeCheckResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Get information on the requirements of a registrant change.
     * 
     * &gt; **Note:** The registrant change API is currently in developer preview and is subject to change.
     * 
     * ## Example Usage
     * 
     * Get registrant change requirements for the `example.com` domain and the contact with ID `1234`:
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.dnsimple.DnsimpleFunctions;
     * import com.pulumi.dnsimple.inputs.GetRegistrantChangeCheckArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = DnsimpleFunctions.getRegistrantChangeCheck(GetRegistrantChangeCheckArgs.builder()
     *             .domainId("example.com")
     *             .contactId("1234")
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static Output<GetRegistrantChangeCheckResult> getRegistrantChangeCheck(GetRegistrantChangeCheckArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("dnsimple:index/getRegistrantChangeCheck:getRegistrantChangeCheck", TypeShape.of(GetRegistrantChangeCheckResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Get information on the requirements of a registrant change.
     * 
     * &gt; **Note:** The registrant change API is currently in developer preview and is subject to change.
     * 
     * ## Example Usage
     * 
     * Get registrant change requirements for the `example.com` domain and the contact with ID `1234`:
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.dnsimple.DnsimpleFunctions;
     * import com.pulumi.dnsimple.inputs.GetRegistrantChangeCheckArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = DnsimpleFunctions.getRegistrantChangeCheck(GetRegistrantChangeCheckArgs.builder()
     *             .domainId("example.com")
     *             .contactId("1234")
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static CompletableFuture<GetRegistrantChangeCheckResult> getRegistrantChangeCheckPlain(GetRegistrantChangeCheckPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("dnsimple:index/getRegistrantChangeCheck:getRegistrantChangeCheck", TypeShape.of(GetRegistrantChangeCheckResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Get information about a DNSimple zone.
     * 
     * It is generally preferable to use the `dnsimple.Zone` resource, but you may wish to only retrieve and link the zone information when the resource exists in multiple Terraform projects.
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.dnsimple.DnsimpleFunctions;
     * import com.pulumi.dnsimple.inputs.GetZoneArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = DnsimpleFunctions.getZone(GetZoneArgs.builder()
     *             .name("example.com")
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static Output<GetZoneResult> getZone(GetZoneArgs args) {
        return getZone(args, InvokeOptions.Empty);
    }
    /**
     * Get information about a DNSimple zone.
     * 
     * It is generally preferable to use the `dnsimple.Zone` resource, but you may wish to only retrieve and link the zone information when the resource exists in multiple Terraform projects.
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.dnsimple.DnsimpleFunctions;
     * import com.pulumi.dnsimple.inputs.GetZoneArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = DnsimpleFunctions.getZone(GetZoneArgs.builder()
     *             .name("example.com")
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static CompletableFuture<GetZoneResult> getZonePlain(GetZonePlainArgs args) {
        return getZonePlain(args, InvokeOptions.Empty);
    }
    /**
     * Get information about a DNSimple zone.
     * 
     * It is generally preferable to use the `dnsimple.Zone` resource, but you may wish to only retrieve and link the zone information when the resource exists in multiple Terraform projects.
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.dnsimple.DnsimpleFunctions;
     * import com.pulumi.dnsimple.inputs.GetZoneArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = DnsimpleFunctions.getZone(GetZoneArgs.builder()
     *             .name("example.com")
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static Output<GetZoneResult> getZone(GetZoneArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("dnsimple:index/getZone:getZone", TypeShape.of(GetZoneResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Get information about a DNSimple zone.
     * 
     * It is generally preferable to use the `dnsimple.Zone` resource, but you may wish to only retrieve and link the zone information when the resource exists in multiple Terraform projects.
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.dnsimple.DnsimpleFunctions;
     * import com.pulumi.dnsimple.inputs.GetZoneArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = DnsimpleFunctions.getZone(GetZoneArgs.builder()
     *             .name("example.com")
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static Output<GetZoneResult> getZone(GetZoneArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("dnsimple:index/getZone:getZone", TypeShape.of(GetZoneResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Get information about a DNSimple zone.
     * 
     * It is generally preferable to use the `dnsimple.Zone` resource, but you may wish to only retrieve and link the zone information when the resource exists in multiple Terraform projects.
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.dnsimple.DnsimpleFunctions;
     * import com.pulumi.dnsimple.inputs.GetZoneArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = DnsimpleFunctions.getZone(GetZoneArgs.builder()
     *             .name("example.com")
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static CompletableFuture<GetZoneResult> getZonePlain(GetZonePlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("dnsimple:index/getZone:getZone", TypeShape.of(GetZoneResult.class), args, Utilities.withVersion(options));
    }
}
