// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dnsimple;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.dnsimple.Utilities;
import com.pulumi.dnsimple.inputs.GetCertificateArgs;
import com.pulumi.dnsimple.inputs.GetCertificatePlainArgs;
import com.pulumi.dnsimple.inputs.GetRegistrantChangeCheckArgs;
import com.pulumi.dnsimple.inputs.GetRegistrantChangeCheckPlainArgs;
import com.pulumi.dnsimple.inputs.GetZoneArgs;
import com.pulumi.dnsimple.inputs.GetZonePlainArgs;
import com.pulumi.dnsimple.outputs.GetCertificateResult;
import com.pulumi.dnsimple.outputs.GetRegistrantChangeCheckResult;
import com.pulumi.dnsimple.outputs.GetZoneResult;
import java.util.concurrent.CompletableFuture;

public final class DnsimpleFunctions {
    public static Output<GetCertificateResult> getCertificate(GetCertificateArgs args) {
        return getCertificate(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetCertificateResult> getCertificatePlain(GetCertificatePlainArgs args) {
        return getCertificatePlain(args, InvokeOptions.Empty);
    }
    public static Output<GetCertificateResult> getCertificate(GetCertificateArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("dnsimple:index/getCertificate:getCertificate", TypeShape.of(GetCertificateResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<GetCertificateResult> getCertificatePlain(GetCertificatePlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("dnsimple:index/getCertificate:getCertificate", TypeShape.of(GetCertificateResult.class), args, Utilities.withVersion(options));
    }
    public static Output<GetRegistrantChangeCheckResult> getRegistrantChangeCheck(GetRegistrantChangeCheckArgs args) {
        return getRegistrantChangeCheck(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetRegistrantChangeCheckResult> getRegistrantChangeCheckPlain(GetRegistrantChangeCheckPlainArgs args) {
        return getRegistrantChangeCheckPlain(args, InvokeOptions.Empty);
    }
    public static Output<GetRegistrantChangeCheckResult> getRegistrantChangeCheck(GetRegistrantChangeCheckArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("dnsimple:index/getRegistrantChangeCheck:getRegistrantChangeCheck", TypeShape.of(GetRegistrantChangeCheckResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<GetRegistrantChangeCheckResult> getRegistrantChangeCheckPlain(GetRegistrantChangeCheckPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("dnsimple:index/getRegistrantChangeCheck:getRegistrantChangeCheck", TypeShape.of(GetRegistrantChangeCheckResult.class), args, Utilities.withVersion(options));
    }
    public static Output<GetZoneResult> getZone(GetZoneArgs args) {
        return getZone(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetZoneResult> getZonePlain(GetZonePlainArgs args) {
        return getZonePlain(args, InvokeOptions.Empty);
    }
    public static Output<GetZoneResult> getZone(GetZoneArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("dnsimple:index/getZone:getZone", TypeShape.of(GetZoneResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<GetZoneResult> getZonePlain(GetZonePlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("dnsimple:index/getZone:getZone", TypeShape.of(GetZoneResult.class), args, Utilities.withVersion(options));
    }
}
