// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dnsimple;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.dnsimple.DsRecordArgs;
import com.pulumi.dnsimple.Utilities;
import com.pulumi.dnsimple.inputs.DsRecordState;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="dnsimple:index/dsRecord:DsRecord")
public class DsRecord extends com.pulumi.resources.CustomResource {
    @Export(name="algorithm", refs={String.class}, tree="[0]")
    private Output<String> algorithm;

    public Output<String> algorithm() {
        return this.algorithm;
    }
    @Export(name="createdAt", refs={String.class}, tree="[0]")
    private Output<String> createdAt;

    public Output<String> createdAt() {
        return this.createdAt;
    }
    @Export(name="digest", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> digest;

    public Output<Optional<String>> digest() {
        return Codegen.optional(this.digest);
    }
    @Export(name="digestType", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> digestType;

    public Output<Optional<String>> digestType() {
        return Codegen.optional(this.digestType);
    }
    @Export(name="domain", refs={String.class}, tree="[0]")
    private Output<String> domain;

    public Output<String> domain() {
        return this.domain;
    }
    @Export(name="keytag", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> keytag;

    public Output<Optional<String>> keytag() {
        return Codegen.optional(this.keytag);
    }
    @Export(name="publicKey", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> publicKey;

    public Output<Optional<String>> publicKey() {
        return Codegen.optional(this.publicKey);
    }
    @Export(name="updatedAt", refs={String.class}, tree="[0]")
    private Output<String> updatedAt;

    public Output<String> updatedAt() {
        return this.updatedAt;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public DsRecord(String name) {
        this(name, DsRecordArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public DsRecord(String name, DsRecordArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public DsRecord(String name, DsRecordArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dnsimple:index/dsRecord:DsRecord", name, args == null ? DsRecordArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private DsRecord(String name, Output<String> id, @Nullable DsRecordState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dnsimple:index/dsRecord:DsRecord", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static DsRecord get(String name, Output<String> id, @Nullable DsRecordState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new DsRecord(name, id, state, options);
    }
}
