provider: dnsimple
major-version: 4
upstreamProviderOrg: dnsimple
esc:
    enabled: true
env:
    DNSIMPLE_TOKEN: ${{ secrets.DNSIMPLE_TOKEN }}
    DNSIMPLE_ACCOUNT: ${{ secrets.DNSIMPLE_ACCOUNT }}
makeTemplate: bridged
team: ecosystem
pulumiConvert: 1
registryDocs: true
