// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DNSimple
{
    /// <summary>
    /// Provides a DNSimple domain delegation signer record resource.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using DNSimple = Pulumi.DNSimple;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new DNSimple.DsRecord("example", new()
    ///     {
    ///         Domain = "example.com",
    ///         Algorithm = "8",
    ///         Digest = "6CEEA0117A02480216EBF745A7B690F938860074E4AD11AF2AC573007205682B",
    ///         DigestType = "2",
    ///         KeyTag = "12345",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// DNSimple DS records can be imported using the domain name and numeric record ID in the format `domain_name_record_id`.
    /// 
    /// bash
    /// 
    /// ```sh
    /// $ pulumi import dnsimple:index/dsRecord:DsRecord example example.com_5678
    /// ```
    /// 
    /// The record ID can be found within the [DNSimple DNSSEC API](https://developer.dnsimple.com/v2/domains/dnssec/#listDomainDelegationSignerRecords). Check out [Authentication](https://developer.dnsimple.com/v2/#authentication) in API Overview for available options.
    /// </summary>
    [DNSimpleResourceType("dnsimple:index/dsRecord:DsRecord")]
    public partial class DsRecord : global::Pulumi.CustomResource
    {
        /// <summary>
        /// DNSSEC algorithm number as a string.
        /// </summary>
        [Output("algorithm")]
        public Output<string> Algorithm { get; private set; } = null!;

        /// <summary>
        /// The timestamp when the DS record was created.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// The hexadecimal representation of the digest of the corresponding DNSKEY record.
        /// </summary>
        [Output("digest")]
        public Output<string?> Digest { get; private set; } = null!;

        /// <summary>
        /// DNSSEC digest type number as a string.
        /// </summary>
        [Output("digestType")]
        public Output<string?> DigestType { get; private set; } = null!;

        /// <summary>
        /// The domain name or numeric ID to create the delegation signer record for.
        /// </summary>
        [Output("domain")]
        public Output<string> Domain { get; private set; } = null!;

        /// <summary>
        /// A key tag that references the corresponding DNSKEY record.
        /// </summary>
        [Output("keyTag")]
        public Output<string?> KeyTag { get; private set; } = null!;

        /// <summary>
        /// A public key that references the corresponding DNSKEY record.
        /// </summary>
        [Output("publicKey")]
        public Output<string?> PublicKey { get; private set; } = null!;

        /// <summary>
        /// The timestamp when the DS record was last updated.
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;


        /// <summary>
        /// Create a DsRecord resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DsRecord(string name, DsRecordArgs args, CustomResourceOptions? options = null)
            : base("dnsimple:index/dsRecord:DsRecord", name, args ?? new DsRecordArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DsRecord(string name, Input<string> id, DsRecordState? state = null, CustomResourceOptions? options = null)
            : base("dnsimple:index/dsRecord:DsRecord", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DsRecord resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DsRecord Get(string name, Input<string> id, DsRecordState? state = null, CustomResourceOptions? options = null)
        {
            return new DsRecord(name, id, state, options);
        }
    }

    public sealed class DsRecordArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// DNSSEC algorithm number as a string.
        /// </summary>
        [Input("algorithm", required: true)]
        public Input<string> Algorithm { get; set; } = null!;

        /// <summary>
        /// The hexadecimal representation of the digest of the corresponding DNSKEY record.
        /// </summary>
        [Input("digest")]
        public Input<string>? Digest { get; set; }

        /// <summary>
        /// DNSSEC digest type number as a string.
        /// </summary>
        [Input("digestType")]
        public Input<string>? DigestType { get; set; }

        /// <summary>
        /// The domain name or numeric ID to create the delegation signer record for.
        /// </summary>
        [Input("domain", required: true)]
        public Input<string> Domain { get; set; } = null!;

        /// <summary>
        /// A key tag that references the corresponding DNSKEY record.
        /// </summary>
        [Input("keyTag")]
        public Input<string>? KeyTag { get; set; }

        /// <summary>
        /// A public key that references the corresponding DNSKEY record.
        /// </summary>
        [Input("publicKey")]
        public Input<string>? PublicKey { get; set; }

        public DsRecordArgs()
        {
        }
        public static new DsRecordArgs Empty => new DsRecordArgs();
    }

    public sealed class DsRecordState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// DNSSEC algorithm number as a string.
        /// </summary>
        [Input("algorithm")]
        public Input<string>? Algorithm { get; set; }

        /// <summary>
        /// The timestamp when the DS record was created.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// The hexadecimal representation of the digest of the corresponding DNSKEY record.
        /// </summary>
        [Input("digest")]
        public Input<string>? Digest { get; set; }

        /// <summary>
        /// DNSSEC digest type number as a string.
        /// </summary>
        [Input("digestType")]
        public Input<string>? DigestType { get; set; }

        /// <summary>
        /// The domain name or numeric ID to create the delegation signer record for.
        /// </summary>
        [Input("domain")]
        public Input<string>? Domain { get; set; }

        /// <summary>
        /// A key tag that references the corresponding DNSKEY record.
        /// </summary>
        [Input("keyTag")]
        public Input<string>? KeyTag { get; set; }

        /// <summary>
        /// A public key that references the corresponding DNSKEY record.
        /// </summary>
        [Input("publicKey")]
        public Input<string>? PublicKey { get; set; }

        /// <summary>
        /// The timestamp when the DS record was last updated.
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        public DsRecordState()
        {
        }
        public static new DsRecordState Empty => new DsRecordState();
    }
}
