// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DNSimple
{
    [DNSimpleResourceType("dnsimple:index/dsRecord:DsRecord")]
    public partial class DsRecord : global::Pulumi.CustomResource
    {
        [Output("algorithm")]
        public Output<string> Algorithm { get; private set; } = null!;

        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        [Output("digest")]
        public Output<string?> Digest { get; private set; } = null!;

        [Output("digestType")]
        public Output<string?> DigestType { get; private set; } = null!;

        [Output("domain")]
        public Output<string> Domain { get; private set; } = null!;

        [Output("keytag")]
        public Output<string?> Keytag { get; private set; } = null!;

        [Output("publicKey")]
        public Output<string?> PublicKey { get; private set; } = null!;

        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;


        /// <summary>
        /// Create a DsRecord resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DsRecord(string name, DsRecordArgs args, CustomResourceOptions? options = null)
            : base("dnsimple:index/dsRecord:DsRecord", name, args ?? new DsRecordArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DsRecord(string name, Input<string> id, DsRecordState? state = null, CustomResourceOptions? options = null)
            : base("dnsimple:index/dsRecord:DsRecord", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DsRecord resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DsRecord Get(string name, Input<string> id, DsRecordState? state = null, CustomResourceOptions? options = null)
        {
            return new DsRecord(name, id, state, options);
        }
    }

    public sealed class DsRecordArgs : global::Pulumi.ResourceArgs
    {
        [Input("algorithm", required: true)]
        public Input<string> Algorithm { get; set; } = null!;

        [Input("digest")]
        public Input<string>? Digest { get; set; }

        [Input("digestType")]
        public Input<string>? DigestType { get; set; }

        [Input("domain", required: true)]
        public Input<string> Domain { get; set; } = null!;

        [Input("keytag")]
        public Input<string>? Keytag { get; set; }

        [Input("publicKey")]
        public Input<string>? PublicKey { get; set; }

        public DsRecordArgs()
        {
        }
        public static new DsRecordArgs Empty => new DsRecordArgs();
    }

    public sealed class DsRecordState : global::Pulumi.ResourceArgs
    {
        [Input("algorithm")]
        public Input<string>? Algorithm { get; set; }

        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        [Input("digest")]
        public Input<string>? Digest { get; set; }

        [Input("digestType")]
        public Input<string>? DigestType { get; set; }

        [Input("domain")]
        public Input<string>? Domain { get; set; }

        [Input("keytag")]
        public Input<string>? Keytag { get; set; }

        [Input("publicKey")]
        public Input<string>? PublicKey { get; set; }

        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        public DsRecordState()
        {
        }
        public static new DsRecordState Empty => new DsRecordState();
    }
}
