// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DNSimple
{
    [DNSimpleResourceType("dnsimple:index/letsEncryptCertificate:LetsEncryptCertificate")]
    public partial class LetsEncryptCertificate : global::Pulumi.CustomResource
    {
        [Output("authorityIdentifier")]
        public Output<string> AuthorityIdentifier { get; private set; } = null!;

        [Output("autoRenew")]
        public Output<bool> AutoRenew { get; private set; } = null!;

        [Output("contactId")]
        public Output<int?> ContactId { get; private set; } = null!;

        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        [Output("csr")]
        public Output<string> Csr { get; private set; } = null!;

        [Output("domainId")]
        public Output<string?> DomainId { get; private set; } = null!;

        [Output("expiresOn")]
        public Output<string> ExpiresOn { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("state")]
        public Output<string> State { get; private set; } = null!;

        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;

        [Output("years")]
        public Output<int> Years { get; private set; } = null!;


        /// <summary>
        /// Create a LetsEncryptCertificate resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public LetsEncryptCertificate(string name, LetsEncryptCertificateArgs args, CustomResourceOptions? options = null)
            : base("dnsimple:index/letsEncryptCertificate:LetsEncryptCertificate", name, args ?? new LetsEncryptCertificateArgs(), MakeResourceOptions(options, ""))
        {
        }

        private LetsEncryptCertificate(string name, Input<string> id, LetsEncryptCertificateState? state = null, CustomResourceOptions? options = null)
            : base("dnsimple:index/letsEncryptCertificate:LetsEncryptCertificate", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing LetsEncryptCertificate resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static LetsEncryptCertificate Get(string name, Input<string> id, LetsEncryptCertificateState? state = null, CustomResourceOptions? options = null)
        {
            return new LetsEncryptCertificate(name, id, state, options);
        }
    }

    public sealed class LetsEncryptCertificateArgs : global::Pulumi.ResourceArgs
    {
        [Input("autoRenew", required: true)]
        public Input<bool> AutoRenew { get; set; } = null!;

        [Input("contactId")]
        public Input<int>? ContactId { get; set; }

        [Input("domainId")]
        public Input<string>? DomainId { get; set; }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public LetsEncryptCertificateArgs()
        {
        }
        public static new LetsEncryptCertificateArgs Empty => new LetsEncryptCertificateArgs();
    }

    public sealed class LetsEncryptCertificateState : global::Pulumi.ResourceArgs
    {
        [Input("authorityIdentifier")]
        public Input<string>? AuthorityIdentifier { get; set; }

        [Input("autoRenew")]
        public Input<bool>? AutoRenew { get; set; }

        [Input("contactId")]
        public Input<int>? ContactId { get; set; }

        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        [Input("csr")]
        public Input<string>? Csr { get; set; }

        [Input("domainId")]
        public Input<string>? DomainId { get; set; }

        [Input("expiresOn")]
        public Input<string>? ExpiresOn { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("state")]
        public Input<string>? State { get; set; }

        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        [Input("years")]
        public Input<int>? Years { get; set; }

        public LetsEncryptCertificateState()
        {
        }
        public static new LetsEncryptCertificateState Empty => new LetsEncryptCertificateState();
    }
}
