# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

account: Optional[str]
"""
The account for API operations.
"""

sandbox: Optional[bool]
"""
Flag to enable the sandbox API.
"""

token: Optional[str]
"""
The API v2 token for API operations.
"""

