// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
	"github.com/pulumi/pulumi/sdk/go/pulumi/config"
)

// The account for API operations.
func GetAccount(ctx *pulumi.Context) string {
	return config.Get(ctx, "dnsimple:account")
}

// The DNSimple account email address.
func GetEmail(ctx *pulumi.Context) string {
	return config.Get(ctx, "dnsimple:email")
}

// The API v2 token for API operations.
func GetToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "dnsimple:token")
}
