// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi-dnsimple/sdk/v4/go/dnsimple/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The account for API operations.
func GetAccount(ctx *pulumi.Context) string {
	return config.Get(ctx, "dnsimple:account")
}

// Flag to enable the prefetch of zone records.
func GetPrefetch(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "dnsimple:prefetch")
}

// Flag to enable the sandbox API.
func GetSandbox(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "dnsimple:sandbox")
}

// The API v2 token for API operations.
func GetToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "dnsimple:token")
}

// Custom string to append to the user agent used for sending HTTP requests to the API.
func GetUserAgent(ctx *pulumi.Context) string {
	return config.Get(ctx, "dnsimple:userAgent")
}
