// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DNSimple.Outputs
{

    [OutputType]
    public sealed class GetRegistrantChangeCheckExtendedAttributeOptionResult
    {
        /// <summary>
        /// (String) - The description of the option.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// (String) - The human-readable title of the option, e.g., `Australian Company Number (ACN)`.
        /// </summary>
        public readonly string Title;
        /// <summary>
        /// (String) - The value of the option.
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private GetRegistrantChangeCheckExtendedAttributeOptionResult(
            string description,

            string title,

            string value)
        {
            Description = description;
            Title = title;
            Value = value;
        }
    }
}
