// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DNSimple.Outputs
{

    [OutputType]
    public sealed class RegisteredDomainDomainRegistration
    {
        public readonly int? Id;
        public readonly int? Period;
        public readonly string? State;

        [OutputConstructor]
        private RegisteredDomainDomainRegistration(
            int? id,

            int? period,

            string? state)
        {
            Id = id;
            Period = period;
            State = state;
        }
    }
}
