// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DNSimple.Outputs
{

    [OutputType]
    public sealed class RegisteredDomainTimeouts
    {
        /// <summary>
        /// The timeout for the read operation e.g. `5m`
        /// </summary>
        public readonly string? Create;
        public readonly string? Delete;
        /// <summary>
        /// The timeout for the read operation e.g. `5m`
        /// 
        /// &lt;a id="nestedblock--domain_registration"&gt;&lt;/a&gt;
        /// </summary>
        public readonly string? Update;

        [OutputConstructor]
        private RegisteredDomainTimeouts(
            string? create,

            string? delete,

            string? update)
        {
            Create = create;
            Delete = delete;
            Update = update;
        }
    }
}
