# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from enum import Enum

__all__ = [
    'RecordTypes',
]


class RecordTypes(str, Enum):
    """
    DNS Record types.
    """
    A = "A"
    AAAA = "AAAA"
    ALIAS = "ALIAS"
    CAA = "CAA"
    CNAME = "CNAME"
    HINFO = "HINFO"
    MX = "MX"
    NAPTR = "NAPTR"
    NS = "NS"
    POOL = "POOL"
    PTR = "PTR"
    SPF = "SPF"
    SRV = "SRV"
    SSHFP = "SSHFP"
    TXT = "TXT"
    URL = "URL"
