name: Download the provider binary
description: Downloads the provider binary to `bin/`.

runs:
  using: "composite"
  steps:

    - name: Download pulumi-resource-dnsimple
      uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
      with:
        pattern: pulumi-resource-dnsimple-*-linux-amd64.tar.gz
        path: ${{ github.workspace }}/bin
        merge-multiple: true

    - name: Untar pulumi-resource-dnsimple
      shell: bash
      run: |
        tar -zxf ${{ github.workspace }}/bin/*amd64.tar.gz -C ${{ github.workspace}}/bin

    - name: Mark pulumi-resource-dnsimple as executable
      shell: bash
      run: |
        find ${{ github.workspace }} -name "pulumi-*-dnsimple" -print -exec chmod +x {} \;
