// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dnsimple

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-dnsimple/sdk/v5/go/dnsimple/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about a DNSimple SSL certificate.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-dnsimple/sdk/v5/go/dnsimple"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := dnsimple.GetCertificate(ctx, &dnsimple.GetCertificateArgs{
//				Domain:        "example.com",
//				CertificateId: 1234,
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetCertificate(ctx *pulumi.Context, args *GetCertificateArgs, opts ...pulumi.InvokeOption) (*GetCertificateResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetCertificateResult
	err := ctx.Invoke("dnsimple:index/getCertificate:getCertificate", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCertificate.
type GetCertificateArgs struct {
	// The ID of the SSL certificate.
	CertificateId int `pulumi:"certificateId"`
	// The domain name of the SSL certificate.
	Domain string `pulumi:"domain"`
	// (see below for nested schema)
	Timeouts *GetCertificateTimeouts `pulumi:"timeouts"`
}

// A collection of values returned by getCertificate.
type GetCertificateResult struct {
	// A list of certificates that make up the certificate chain.
	CertificateChains []string `pulumi:"certificateChains"`
	CertificateId     int      `pulumi:"certificateId"`
	Domain            string   `pulumi:"domain"`
	// The certificate ID.
	Id string `pulumi:"id"`
	// The corresponding private key for the SSL certificate.
	PrivateKey string `pulumi:"privateKey"`
	// The root certificate of the issuing CA.
	RootCertificate string `pulumi:"rootCertificate"`
	// The SSL certificate.
	ServerCertificate string                  `pulumi:"serverCertificate"`
	Timeouts          *GetCertificateTimeouts `pulumi:"timeouts"`
}

func GetCertificateOutput(ctx *pulumi.Context, args GetCertificateOutputArgs, opts ...pulumi.InvokeOption) GetCertificateResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetCertificateResultOutput, error) {
			args := v.(GetCertificateArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("dnsimple:index/getCertificate:getCertificate", args, GetCertificateResultOutput{}, options).(GetCertificateResultOutput), nil
		}).(GetCertificateResultOutput)
}

// A collection of arguments for invoking getCertificate.
type GetCertificateOutputArgs struct {
	// The ID of the SSL certificate.
	CertificateId pulumi.IntInput `pulumi:"certificateId"`
	// The domain name of the SSL certificate.
	Domain pulumi.StringInput `pulumi:"domain"`
	// (see below for nested schema)
	Timeouts GetCertificateTimeoutsPtrInput `pulumi:"timeouts"`
}

func (GetCertificateOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCertificateArgs)(nil)).Elem()
}

// A collection of values returned by getCertificate.
type GetCertificateResultOutput struct{ *pulumi.OutputState }

func (GetCertificateResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCertificateResult)(nil)).Elem()
}

func (o GetCertificateResultOutput) ToGetCertificateResultOutput() GetCertificateResultOutput {
	return o
}

func (o GetCertificateResultOutput) ToGetCertificateResultOutputWithContext(ctx context.Context) GetCertificateResultOutput {
	return o
}

// A list of certificates that make up the certificate chain.
func (o GetCertificateResultOutput) CertificateChains() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetCertificateResult) []string { return v.CertificateChains }).(pulumi.StringArrayOutput)
}

func (o GetCertificateResultOutput) CertificateId() pulumi.IntOutput {
	return o.ApplyT(func(v GetCertificateResult) int { return v.CertificateId }).(pulumi.IntOutput)
}

func (o GetCertificateResultOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v GetCertificateResult) string { return v.Domain }).(pulumi.StringOutput)
}

// The certificate ID.
func (o GetCertificateResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetCertificateResult) string { return v.Id }).(pulumi.StringOutput)
}

// The corresponding private key for the SSL certificate.
func (o GetCertificateResultOutput) PrivateKey() pulumi.StringOutput {
	return o.ApplyT(func(v GetCertificateResult) string { return v.PrivateKey }).(pulumi.StringOutput)
}

// The root certificate of the issuing CA.
func (o GetCertificateResultOutput) RootCertificate() pulumi.StringOutput {
	return o.ApplyT(func(v GetCertificateResult) string { return v.RootCertificate }).(pulumi.StringOutput)
}

// The SSL certificate.
func (o GetCertificateResultOutput) ServerCertificate() pulumi.StringOutput {
	return o.ApplyT(func(v GetCertificateResult) string { return v.ServerCertificate }).(pulumi.StringOutput)
}

func (o GetCertificateResultOutput) Timeouts() GetCertificateTimeoutsPtrOutput {
	return o.ApplyT(func(v GetCertificateResult) *GetCertificateTimeouts { return v.Timeouts }).(GetCertificateTimeoutsPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetCertificateResultOutput{})
}
