// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DNSimple.Inputs
{

    public sealed class GetCertificateTimeoutsInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// (String) - The timeout for the read operation, e.g., `5m`.
        /// </summary>
        [Input("read")]
        public Input<string>? Read { get; set; }

        public GetCertificateTimeoutsInputArgs()
        {
        }
        public static new GetCertificateTimeoutsInputArgs Empty => new GetCertificateTimeoutsInputArgs();
    }
}
