// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DNSimple.Inputs
{

    public sealed class RegisteredDomainRegistrantChangeArgs : global::Pulumi.ResourceArgs
    {
        [Input("accountId")]
        public Input<int>? AccountId { get; set; }

        [Input("contactId")]
        public Input<int>? ContactId { get; set; }

        [Input("domainId")]
        public Input<string>? DomainId { get; set; }

        [Input("extendedAttributes")]
        private InputMap<string>? _extendedAttributes;
        public InputMap<string> ExtendedAttributes
        {
            get => _extendedAttributes ?? (_extendedAttributes = new InputMap<string>());
            set => _extendedAttributes = value;
        }

        [Input("id")]
        public Input<int>? Id { get; set; }

        [Input("irtLockLiftedBy")]
        public Input<string>? IrtLockLiftedBy { get; set; }

        [Input("registryOwnerChange")]
        public Input<bool>? RegistryOwnerChange { get; set; }

        [Input("state")]
        public Input<string>? State { get; set; }

        public RegisteredDomainRegistrantChangeArgs()
        {
        }
        public static new RegisteredDomainRegistrantChangeArgs Empty => new RegisteredDomainRegistrantChangeArgs();
    }
}
