// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DNSimple.Inputs
{

    public sealed class RegisteredDomainRegistrantChangeGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("accountId")]
        public Input<int>? AccountId { get; set; }

        /// <summary>
        /// The ID of the contact to be used for the domain registration. The contact ID can be changed after the domain has been registered. The change will result in a new registrant change this may result in a [60-day lock](https://support.dnsimple.com/articles/icann-60-day-lock-registrant-change/).
        /// </summary>
        [Input("contactId")]
        public Input<int>? ContactId { get; set; }

        [Input("domainId")]
        public Input<string>? DomainId { get; set; }

        [Input("extendedAttributes")]
        private InputMap<string>? _extendedAttributes;

        /// <summary>
        /// A map of extended attributes to be set for the domain registration. To see if there are any required extended attributes for any TLD use our [Lists the TLD Extended Attributes API](https://developer.dnsimple.com/v2/tlds/#getTldExtendedAttributes). The values provided in the `extended_attributes` will also be sent when a registrant change is initiated as part of changing the `contact_id`.
        /// </summary>
        public InputMap<string> ExtendedAttributes
        {
            get => _extendedAttributes ?? (_extendedAttributes = new InputMap<string>());
            set => _extendedAttributes = value;
        }

        /// <summary>
        /// The ID of this resource.
        /// </summary>
        [Input("id")]
        public Input<int>? Id { get; set; }

        [Input("irtLockLiftedBy")]
        public Input<string>? IrtLockLiftedBy { get; set; }

        [Input("registryOwnerChange")]
        public Input<bool>? RegistryOwnerChange { get; set; }

        /// <summary>
        /// The state of the domain.
        /// </summary>
        [Input("state")]
        public Input<string>? State { get; set; }

        public RegisteredDomainRegistrantChangeGetArgs()
        {
        }
        public static new RegisteredDomainRegistrantChangeGetArgs Empty => new RegisteredDomainRegistrantChangeGetArgs();
    }
}
