// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dnsimple.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RegisteredDomainDomainRegistrationArgs extends com.pulumi.resources.ResourceArgs {

    public static final RegisteredDomainDomainRegistrationArgs Empty = new RegisteredDomainDomainRegistrationArgs();

    /**
     * (Number) - The ID of the domain registration.
     * 
     */
    @Import(name="id")
    private @Nullable Output<Integer> id;

    /**
     * @return (Number) - The ID of the domain registration.
     * 
     */
    public Optional<Output<Integer>> id() {
        return Optional.ofNullable(this.id);
    }

    /**
     * (Number) - The registration period in years.
     * 
     */
    @Import(name="period")
    private @Nullable Output<Integer> period;

    /**
     * @return (Number) - The registration period in years.
     * 
     */
    public Optional<Output<Integer>> period() {
        return Optional.ofNullable(this.period);
    }

    /**
     * (String) - The state of the domain registration.
     * 
     */
    @Import(name="state")
    private @Nullable Output<String> state;

    /**
     * @return (String) - The state of the domain registration.
     * 
     */
    public Optional<Output<String>> state() {
        return Optional.ofNullable(this.state);
    }

    private RegisteredDomainDomainRegistrationArgs() {}

    private RegisteredDomainDomainRegistrationArgs(RegisteredDomainDomainRegistrationArgs $) {
        this.id = $.id;
        this.period = $.period;
        this.state = $.state;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RegisteredDomainDomainRegistrationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RegisteredDomainDomainRegistrationArgs $;

        public Builder() {
            $ = new RegisteredDomainDomainRegistrationArgs();
        }

        public Builder(RegisteredDomainDomainRegistrationArgs defaults) {
            $ = new RegisteredDomainDomainRegistrationArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id (Number) - The ID of the domain registration.
         * 
         * @return builder
         * 
         */
        public Builder id(@Nullable Output<Integer> id) {
            $.id = id;
            return this;
        }

        /**
         * @param id (Number) - The ID of the domain registration.
         * 
         * @return builder
         * 
         */
        public Builder id(Integer id) {
            return id(Output.of(id));
        }

        /**
         * @param period (Number) - The registration period in years.
         * 
         * @return builder
         * 
         */
        public Builder period(@Nullable Output<Integer> period) {
            $.period = period;
            return this;
        }

        /**
         * @param period (Number) - The registration period in years.
         * 
         * @return builder
         * 
         */
        public Builder period(Integer period) {
            return period(Output.of(period));
        }

        /**
         * @param state (String) - The state of the domain registration.
         * 
         * @return builder
         * 
         */
        public Builder state(@Nullable Output<String> state) {
            $.state = state;
            return this;
        }

        /**
         * @param state (String) - The state of the domain registration.
         * 
         * @return builder
         * 
         */
        public Builder state(String state) {
            return state(Output.of(state));
        }

        public RegisteredDomainDomainRegistrationArgs build() {
            return $;
        }
    }

}
