// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dnsimple.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RegisteredDomainTimeoutsArgs extends com.pulumi.resources.ResourceArgs {

    public static final RegisteredDomainTimeoutsArgs Empty = new RegisteredDomainTimeoutsArgs();

    /**
     * The timeout for the read operation e.g. `5m`
     * 
     */
    @Import(name="create")
    private @Nullable Output<String> create;

    /**
     * @return The timeout for the read operation e.g. `5m`
     * 
     */
    public Optional<Output<String>> create() {
        return Optional.ofNullable(this.create);
    }

    @Import(name="delete")
    private @Nullable Output<String> delete;

    public Optional<Output<String>> delete() {
        return Optional.ofNullable(this.delete);
    }

    /**
     * The timeout for the read operation e.g. `5m`
     * 
     * &lt;a id=&#34;nestedblock--domain_registration&#34;&gt;&lt;/a&gt;
     * 
     */
    @Import(name="update")
    private @Nullable Output<String> update;

    /**
     * @return The timeout for the read operation e.g. `5m`
     * 
     * &lt;a id=&#34;nestedblock--domain_registration&#34;&gt;&lt;/a&gt;
     * 
     */
    public Optional<Output<String>> update() {
        return Optional.ofNullable(this.update);
    }

    private RegisteredDomainTimeoutsArgs() {}

    private RegisteredDomainTimeoutsArgs(RegisteredDomainTimeoutsArgs $) {
        this.create = $.create;
        this.delete = $.delete;
        this.update = $.update;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RegisteredDomainTimeoutsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RegisteredDomainTimeoutsArgs $;

        public Builder() {
            $ = new RegisteredDomainTimeoutsArgs();
        }

        public Builder(RegisteredDomainTimeoutsArgs defaults) {
            $ = new RegisteredDomainTimeoutsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param create The timeout for the read operation e.g. `5m`
         * 
         * @return builder
         * 
         */
        public Builder create(@Nullable Output<String> create) {
            $.create = create;
            return this;
        }

        /**
         * @param create The timeout for the read operation e.g. `5m`
         * 
         * @return builder
         * 
         */
        public Builder create(String create) {
            return create(Output.of(create));
        }

        public Builder delete(@Nullable Output<String> delete) {
            $.delete = delete;
            return this;
        }

        public Builder delete(String delete) {
            return delete(Output.of(delete));
        }

        /**
         * @param update The timeout for the read operation e.g. `5m`
         * 
         * &lt;a id=&#34;nestedblock--domain_registration&#34;&gt;&lt;/a&gt;
         * 
         * @return builder
         * 
         */
        public Builder update(@Nullable Output<String> update) {
            $.update = update;
            return this;
        }

        /**
         * @param update The timeout for the read operation e.g. `5m`
         * 
         * &lt;a id=&#34;nestedblock--domain_registration&#34;&gt;&lt;/a&gt;
         * 
         * @return builder
         * 
         */
        public Builder update(String update) {
            return update(Output.of(update));
        }

        public RegisteredDomainTimeoutsArgs build() {
            return $;
        }
    }

}
