// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Provides a DNSimple domain resource.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as dnsimple from "@pulumi/dnsimple";
 *
 * const example = new dnsimple.Domain("example", {name: "example.com"});
 * ```
 *
 * ## Import
 *
 * DNSimple domains can be imported using the domain name.
 *
 * ```sh
 * $ pulumi import dnsimple:index/domain:Domain example example.com
 * ```
 *
 * The domain name can be found within the [DNSimple Domains API](https://developer.dnsimple.com/v2/domains/#listDomains). Check out [Authentication](https://developer.dnsimple.com/v2/#authentication) in API Overview for available options.
 */
export class Domain extends pulumi.CustomResource {
    /**
     * Get an existing Domain resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DomainState, opts?: pulumi.CustomResourceOptions): Domain {
        return new Domain(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'dnsimple:index/domain:Domain';

    /**
     * Returns true if the given object is an instance of Domain.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Domain {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Domain.__pulumiType;
    }

    /**
     * The account ID for the domain.
     */
    declare public /*out*/ readonly accountId: pulumi.Output<number>;
    /**
     * Whether the domain is set to auto-renew.
     */
    declare public /*out*/ readonly autoRenew: pulumi.Output<boolean>;
    /**
     * The domain name to be created.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Whether the domain has WhoIs privacy enabled.
     */
    declare public /*out*/ readonly privateWhois: pulumi.Output<boolean>;
    /**
     * The ID of the registrant (contact) for the domain.
     */
    declare public /*out*/ readonly registrantId: pulumi.Output<number>;
    /**
     * The state of the domain.
     */
    declare public /*out*/ readonly state: pulumi.Output<string>;
    /**
     * The domain name in Unicode format.
     */
    declare public /*out*/ readonly unicodeName: pulumi.Output<string>;

    /**
     * Create a Domain resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DomainArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DomainArgs | DomainState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DomainState | undefined;
            resourceInputs["accountId"] = state?.accountId;
            resourceInputs["autoRenew"] = state?.autoRenew;
            resourceInputs["name"] = state?.name;
            resourceInputs["privateWhois"] = state?.privateWhois;
            resourceInputs["registrantId"] = state?.registrantId;
            resourceInputs["state"] = state?.state;
            resourceInputs["unicodeName"] = state?.unicodeName;
        } else {
            const args = argsOrState as DomainArgs | undefined;
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["accountId"] = undefined /*out*/;
            resourceInputs["autoRenew"] = undefined /*out*/;
            resourceInputs["privateWhois"] = undefined /*out*/;
            resourceInputs["registrantId"] = undefined /*out*/;
            resourceInputs["state"] = undefined /*out*/;
            resourceInputs["unicodeName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Domain.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Domain resources.
 */
export interface DomainState {
    /**
     * The account ID for the domain.
     */
    accountId?: pulumi.Input<number>;
    /**
     * Whether the domain is set to auto-renew.
     */
    autoRenew?: pulumi.Input<boolean>;
    /**
     * The domain name to be created.
     */
    name?: pulumi.Input<string>;
    /**
     * Whether the domain has WhoIs privacy enabled.
     */
    privateWhois?: pulumi.Input<boolean>;
    /**
     * The ID of the registrant (contact) for the domain.
     */
    registrantId?: pulumi.Input<number>;
    /**
     * The state of the domain.
     */
    state?: pulumi.Input<string>;
    /**
     * The domain name in Unicode format.
     */
    unicodeName?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Domain resource.
 */
export interface DomainArgs {
    /**
     * The domain name to be created.
     */
    name: pulumi.Input<string>;
}
