// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./emailForward";
export * from "./provider";
export * from "./record";
export * from "./recordType";

// Export sub-modules:
import * as config from "./config";

export {
    config,
};

// Import resources to register:
import { EmailForward } from "./emailForward";
import { Record } from "./record";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "dnsimple:index/emailForward:EmailForward":
                return new EmailForward(name, <any>undefined, { urn })
            case "dnsimple:index/record:Record":
                return new Record(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("dnsimple", "index/emailForward", _module)
pulumi.runtime.registerResourceModule("dnsimple", "index/record", _module)

import { Provider } from "./provider";

pulumi.runtime.registerResourcePackage("dnsimple", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:dnsimple") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
